db.EMPLOYEE_BLANK.insertMany([
  {
    _id: 1,
    name: "Иван",
    sername: "Иванов",
    father_name: "Иванович",
    email: "ivan@gmail.com",
    telephone_number: "8(777)111-11-11",
    date_of_birth: "Дата рождения: 10.10.1987",
    hobbies: ["плавание", "шахматы"],
    prikaz: {
      info: "Номер уведомления: 123",
    },
  },
  {
    _id: 2,
    name: "Николай",
    sername: "Семерук",
    father_name: "Александрович",
    email: "killer@rambler.ru",
    telephone_number: "7(777)523-68-91",
    hobbies: ["бокс"],
    prikaz: {
      info: "Номер приказа: 1001",
    },
  },
  {
    _id: 3,
    name: "Александр",
    sername: "Хопта",
    father_name: "Петрович",
    email: "sasha@.ru",
    telephone_number: "(2-20-47)",
    date_of_birth: "Дата рождения: 10.07.1987",
    hobbies: ["плавание"],
    prikaz: {
      info: "Номер распоряжения: 202",
    },
  },
  {
    _id: 4,
    name: "Владимир",
    sername: "Никифоров",
    father_name: "Александрович",
    email: "vova@rambler.ru",
    telephone_number: "2-45-48",
    date_of_birth: "Дата рождения: 12.07.1967",
    prikaz: {
      info: "Номер приказа: 404",
    },
  },
  {
    _id: 5,
    name: "Семен",
    sername: "Лобанов",
    father_name: "Иванович",
    email: "semen@yandex.com",
    telephone_number: "8(777)654-12-21",
    date_of_birth: "Дата рождения: 10.01.1987",
    hobbies: ["борьба"],
    prikaz: {
      info: "Номер приказа: 15",
    },
  },
  {
    _id: 6,
    name: "Глеб",
    sername: "Кисегач",
    father_name: "Викторович",
    email: "gleb@mail.",
    telephone_number: "2-87-98",
    hobbies: ["компьютерные игры"],
    prikaz: {
      info: "Номер распоряжения: 333",
    },
  },
  {
    _id: 7,
    name: "Варя",
    sername: "Черноус",
    father_name: "Петрович",
    email: "cher@mail.ru",
    date_of_birth: "Дата рождения: 14.01.1980",
    prikaz: {
      info: "Номер приказа: 1",
    },
  },
]);
